// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qncjjtrmaogzropynjbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuY2pqdHJtYW9nenJvcHluamJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTMwODMsImV4cCI6MjA3MDg4OTA4M30.9IVWxoFQzIVDpWzso4evZfeVGxdoty9cQXSCLp3K2c0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});